steps:
  - name: gradle:7.6.0-jdk11
    entrypoint: gradle
    args: [ 'test' ]
    id: 'run-tests'
    waitFor: [ '-' ]
  - name: gradle:7.6.0-jdk11
    entrypoint: gradle
    args: [ 'build' ]
    id: 'gradle-build'
    waitFor: [ 'run-tests' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ "build", "-t", "asia-south1-docker.pkg.dev/smart-howl-372909/demo-project/customer-service:v1",
            "--build-arg=JAR_FILE=build/libs/customer-service-0.0.1-SNAPSHOT.jar", "." ]
    id: 'build-image-cloudrun'
    waitFor: [ 'gradle-build' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/demo-project/customer-service:v1' ]
    id: 'push-image-to-container-registry'
    waitFor: [ 'build-image-cloudrun' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cloudrun-tf'
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/demo-project/customer-service:v1'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: 'deploy-image-to-cloudrun'
    waitFor: [ 'push-image-to-container-registry' ]

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/demo-project/customer-service:v1'
