steps:
  - - name: 'gcr.io/cloud-builders/docker'
      args:
        - 'build'
        - '--build-arg'
        - 'SONARQUBE_SCANNER_CLI_VERSION=4.6.0.2311'
        - '-t'
        - 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
        - '-t'
        - 'gcr.io/$PROJECT_ID/sonar-scanner:4.6.0.2311'
        - '.'
  - name: gradle:7.6.0-jdk11
    entrypoint: gradle
    args: [ 'test' ]
    id: 'run-tests'
    waitFor: [ '-' ]
  - name: gradle:7.6.0-jdk11
    entrypoint: gradle
    args: [ 'build' ]
    id: 'gradle-build'
    waitFor: [ 'run-tests' ]
  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    id: 'sonar-qube'
    args:
      - '-Dsonar.host.url=https://sonarcloud.io'
      - '-Dsonar.login=3cdfefe54e4389b20de5bea32844c93ad9b3169a'
      - '-Dsonar.projectKey=pavanposannapeta'
      - '-Dsonar.organization=Pavan Posannapeta'
      - '-Dsonar.sources=.'
    waitFor: [ 'gradle-build' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ "build", "-t", "asia-south1-docker.pkg.dev/smart-howl-372909/demo-project/customer-service:$COMMIT_SHA",
            "--build-arg=JAR_FILE=build/libs/customer-service-0.0.1-SNAPSHOT.jar", "." ]
    id: 'build-image-cloudrun'
    waitFor: [ 'gradle-build' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/demo-project/customer-service:$COMMIT_SHA' ]
    id: 'push-image-to-container-registry'
    waitFor: [ 'build-image-cloudrun' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cloudrun-tf'
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/demo-project/customer-service:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: 'deploy-image-to-cloudrun'
    waitFor: [ 'push-image-to-container-registry' ]

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/demo-project/customer-service:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  - 'gcr.io/$PROJECT_ID/sonar-scanner:4.6.0.2311'
