steps:
  - name: gradle:7.6.0-jdk11
    entrypoint: gradle
    args: [ 'test' ]
    id: 'run-tests'
    waitFor: [ '-' ]
  - name: gradle:7.6.0-jdk11
    entrypoint: gradle
    args: [ 'build' ]
    id: 'gradle-build'
    waitFor: [ 'run-tests' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ "build", "-t", "asia-south1-docker.pkg.dev/$PROJECT_ID/customer-service/customer-service:v1",
            "--build-arg=JAR_FILE=build/libs/customer-service-0.0.1-SNAPSHOT.jar", "." ]
    id: 'build-image'
    waitFor: [ 'gradle-build' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/customer-service/customer-service:v1' ]
    id: 'push-image-to-container-registry'
    waitFor: [ 'build-image' ]

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/customer-service/customer-service:v1'
